#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 Leonardo Roman da Rosa
#
# png2scr.py - convert full-screen art into a ZX Spectrum SCR loading screen
# embedded as banked C const data (the +zx port's title/victory screens).
#
#   python tools/png2scr.py            # regenerate every image below
#   python tools/png2scr.py victory    # just one
#
# A ZX SCR is 6912 bytes: a 6144-byte 1bpp bitmap in the Spectrum's
# thirds/interleaved layout, then 768 attribute bytes (one ink/paper/bright per
# 8x8 cell). The art is 256x192. For each 8x8 block we pick the 2 ZX colours
# (sharing one BRIGHT bit, since BRIGHT is per-cell) that best fit the block's
# pixels -- classic "attribute clash" -- then set each pixel's bit to whichever
# of the two it is nearer. Each SCR is const-banked in BANK_4 (both fit: 2*6912
# < 16384); the blitter that copies it to 0x4000 must run in BANK_4 too (see
# src/scr.c), so the banked const is mapped in when it is read.

from PIL import Image
import os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, "..", "src")
W, H = 256, 192

# name -> (source png, C symbol, bank section)
IMAGES = {
    "title":   ("title.png",   "title_scr",   "BANK_4"),
    "victory": ("victory.png", "victory_scr", "BANK_4"),
}


def zx_rgb(color, bright):
    """ZX colour 0..7 (G*4 + R*2 + B*1) at a brightness -> 8-bit RGB."""
    v = 255 if bright else 205
    return (v if (color & 2) else 0,    # red
            v if (color & 4) else 0,    # green
            v if (color & 1) else 0)    # blue


def d2(a, b):
    return (a[0] - b[0]) ** 2 + (a[1] - b[1]) ** 2 + (a[2] - b[2]) ** 2


def convert_block(pixels):
    """64 RGB pixels -> (attribute byte, 64 bits). Tries both BRIGHT values and
    keeps the 2-colour fit with the least squared error."""
    best = None
    for bright in (0, 1):
        pal = [zx_rgb(c, bright) for c in range(8)]
        counts = [0] * 8
        for p in pixels:
            counts[min(range(8), key=lambda c: d2(p, pal[c]))] += 1
        order = sorted(range(8), key=lambda c: -counts[c])
        paper = order[0]
        ink = order[1] if counts[order[1]] > 0 else order[0]
        err, bits = 0, []
        for p in pixels:
            di = d2(p, pal[ink])
            dp = d2(p, pal[paper])
            if di < dp:
                bits.append(1); err += di
            else:
                bits.append(0); err += dp
        if best is None or err < best[0]:
            attr = (ink & 7) | ((paper & 7) << 3) | (bright << 6)
            best = (err, attr, bits)
    return best[1], best[2]


def to_scr(img):
    scr = bytearray(6912)
    for by in range(24):
        for bx in range(32):
            pixels = [img.getpixel((bx * 8 + col, by * 8 + row))
                      for row in range(8) for col in range(8)]
            attr, bits = convert_block(pixels)
            scr[6144 + by * 32 + bx] = attr
            for row in range(8):
                yp = by * 8 + row
                b = 0
                for col in range(8):
                    if bits[row * 8 + col]:
                        b |= (0x80 >> col)
                off = (yp // 64) * 2048 + (yp % 8) * 256 + ((yp // 8) % 8) * 32 + bx
                scr[off] = b
    return scr


def emit(name, sym, seg, data, src):
    with open(os.path.join(ROOT, name), "w", newline="\n") as f:
        f.write("/* SPDX-License-Identifier: GPL-3.0-or-later\n")
        f.write(" * Copyright (C) 2026 Leonardo Roman da Rosa */\n")
        f.write("/* %s - GENERATED by tools/png2scr.py from tools/%s.\n"
                " * Do not edit by hand. A 6912-byte ZX SCR (6144 bitmap +\n"
                " * 768 attributes); banked const, in section %s. */\n\n"
                % (name, src, seg))
        f.write("#include <stdint.h>\n\n")
        f.write("#pragma constseg %s\n" % seg)
        f.write("const uint8_t %s[%d] = {\n" % (sym, len(data)))
        for i in range(0, len(data), 24):
            f.write("  " + ",".join(str(v) for v in data[i:i + 24]) + ",\n")
        f.write("};\n")


def convert(name):
    src, sym, seg = IMAGES[name]
    img = Image.open(os.path.join(HERE, src)).convert("RGB")
    if img.size != (W, H):
        img = img.resize((W, H), Image.LANCZOS)
    scr = to_scr(img)
    emit("%s.c" % sym, sym, seg, list(scr), src)
    print("%s -> src/%s.c  (%d bytes, %s)" % (name, sym, len(scr), seg))


def main():
    for name in (sys.argv[1:] or list(IMAGES)):
        convert(name)


if __name__ == "__main__":
    main()
