#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 Leonardo Roman da Rosa
#
# png2layer2.py - convert the title art into a ZX Spectrum Next Layer 2 image
# embedded as C const data (titlegfx.c).
#
#   python tools/png2layer2.py
#
# Reads tools/title.png (a 4:3 768x576 letterboxed render), produces a 256x192
# 8bpp Layer 2 framebuffer + a 256-entry 9-bit palette, and writes titlegfx.c:
#   - title_img0/1/2[16384]  : the framebuffer, row-major (y*256+x), split into
#                              the three consecutive 16K banks Layer 2 reads.
#   - title_pal[512]         : 2 bytes per colour, ready to stream to NextReg
#                              0x44 (first byte RRRGGGBB, second byte bit0 = blue
#                              LSB) for true 9-bit (RGB333) colour.
# The arrays live in banked const sections (see mmap.inc / nexthack.c), so the
# image costs nothing against the resident memory budget.

from PIL import Image
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SRC  = os.path.join(HERE, "title.png")
ROOT = os.path.join(HERE, "..")

W, H = 256, 192
BANK = 16384

# SDCC's `#pragma constseg` is per-translation-unit (switching it mid-file does
# NOT create separate areas - the last one wins for the whole file). So each
# const lives in its OWN .c file with a single constseg: the three framebuffer
# thirds in three consecutive 16K banks Layer 2 reads in place, and the palette
# in PAGE_22_CODE (bank 11) next to the title code that streams it.
FILES = [
    ("titlegfx0.c", "title_img0", "BANK_16"),
    ("titlegfx1.c", "title_img1", "BANK_17"),
    ("titlegfx2.c", "title_img2", "BANK_18"),
    ("titlepal.c",  "title_pal",  "PAGE_22_CODE"),
]


def rgb333(r, g, b):
    """Snap an 8-bit-per-channel colour to the Next 9-bit (RGB333) grid and
    return the two NextReg bytes: (RRRGGGBB, 0000000B0)."""
    r3 = round(r / 255 * 7)
    g3 = round(g / 255 * 7)
    b3 = round(b / 255 * 7)
    byte1 = (r3 << 5) | (g3 << 2) | (b3 >> 1)   # RRR GGG BB
    byte2 = b3 & 1                               # blue LSB
    return byte1, byte2


def main():
    img = Image.open(SRC).convert("RGB").resize((W, H), Image.LANCZOS)
    # Quantize to <=256 colours with dithering, then snap the palette to RGB333.
    # MAXCOVERAGE (vs MEDIANCUT) keeps small saturated regions a palette slot of
    # their own -- without it the tiny green ZX rainbow stripe gets merged into
    # the abundant yellow/teal and is lost.
    q = img.quantize(colors=256, method=Image.MAXCOVERAGE, dither=Image.FLOYDSTEINBERG)

    pal = q.getpalette()            # 256*3 RGB
    palbytes = []
    for i in range(256):
        b1, b2 = rgb333(pal[i * 3], pal[i * 3 + 1], pal[i * 3 + 2])
        palbytes += [b1, b2]

    idx = list(q.getdata())         # 256*192 palette indices, row-major
    assert len(idx) == W * H, len(idx)

    used = len({(pal[i*3], pal[i*3+1], pal[i*3+2]) for i in set(idx)})

    chunks = {
        "title_img0": idx[0 * BANK:1 * BANK],
        "title_img1": idx[1 * BANK:2 * BANK],
        "title_img2": idx[2 * BANK:3 * BANK],
        "title_pal":  palbytes,
    }

    def emit(fname, name, seg):
        data = chunks[name]
        with open(os.path.join(ROOT, fname), "w", newline="\n") as f:
            f.write("/* SPDX-License-Identifier: GPL-3.0-or-later\n")
            f.write(" * Copyright (C) 2026 Leonardo Roman da Rosa */\n")
            f.write("/* %s - GENERATED by tools/png2layer2.py from tools/title.png.\n"
                    " * Do not edit by hand. Part of the 256x192 Layer 2 title image\n"
                    " * (row-major y*256+x); banked const, in section %s. */\n\n"
                    % (fname, seg))
            f.write("#include <stdint.h>\n\n")
            f.write("#pragma constseg %s\n" % seg)
            f.write("const uint8_t %s[%d] = {\n" % (name, len(data)))
            for i in range(0, len(data), 24):
                f.write("  " + ",".join(str(v) for v in data[i:i + 24]) + ",\n")
            f.write("};\n")

    for fname, name, seg in FILES:
        emit(fname, name, seg)

    print("wrote %s  (%d distinct colours)"
          % (", ".join(f for f, _, _ in FILES), used))


if __name__ == "__main__":
    main()
