#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 Leonardo Roman da Rosa
#
# txt2template.py - pack the hand-drawn special-level maps in
# tools/templates/*.txt into src/leveltmpl_data.h (banked const).
#
#   python tools/txt2template.py
#
# Each .txt is a MAPH x MAPW ASCII map using the normal terrain chars
# ('.' '#' '-' '|' '+' '<' '>' ' '), preceded by metadata comment lines:
#   ;name:  <label>                      (optional, for the C comment)
#   ;rooms: x,y,w,h [x,y,w,h ...]        (1..3 room rects FOV should light)
# Rows shorter than MAPW are padded with rock; missing trailing rows are rock.

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import lztmpl

HERE = Path(__file__).resolve().parent
TDIR = HERE / "templates"
OUT  = HERE.parent / "src" / "leveltmpl_data.h"
MAPW, MAPH = 80, 21
MAXROOM = 6


def load(path):
    name = path.stem
    rooms, rows = [], []
    for line in path.read_text().splitlines():
        if line.startswith(";rooms:"):
            rooms = [tuple(int(v) for v in tok.split(","))
                     for tok in line[len(";rooms:"):].split()]
        elif line.startswith(";"):
            continue
        else:
            rows.append(line)
    if len(rows) > MAPH:
        raise SystemExit(f"{name}: {len(rows)} map rows > {MAPH}")
    rows += [""] * (MAPH - len(rows))                 # pad trailing rock rows
    grid = []
    for i, r in enumerate(rows):
        if len(r) > MAPW:
            raise SystemExit(f"{name}: row {i} is {len(r)} > {MAPW} cols")
        grid.append(r.ljust(MAPW))
    if not (1 <= len(rooms) <= MAXROOM):
        raise SystemExit(f"{name}: need 1..{MAXROOM} room rects, got {len(rooms)}")
    for (x, y, w, h) in rooms:
        if x + w > MAPW or y + h > MAPH:
            raise SystemExit(f"{name}: room {x},{y},{w},{h} out of bounds")
    return name, grid, rooms


def main():
    tmpls = [load(p) for p in sorted(TDIR.glob("*.txt"))]
    if not tmpls:
        raise SystemExit("no templates in " + str(TDIR))
    with OUT.open("w", newline="\n") as f:
        f.write("/* SPDX-License-Identifier: GPL-3.0-or-later\n")
        f.write(" * Copyright (C) 2026 Leonardo Roman da Rosa */\n")
        f.write("/* leveltmpl_data.h - GENERATED by tools/txt2template.py from\n")
        f.write(" * tools/templates/*.txt. Do not edit by hand. Hand-drawn special-\n")
        f.write(" * level maps (MAPH x MAPW) + their room rects, included once into\n")
        f.write(" * the banked leveltmpl.c as const; banks.json says which\n")
        f.write(" * bank, and load_template() runs from that same one. */\n\n")
        f.write("#define NTMPL %d\n\n" % len(tmpls))

        # The grids are LZ-packed (tools/lztmpl.py) and expanded straight into
        # lvl[][] by load_template, which was going to write those 1680 bytes
        # anyway -- so the destination costs nothing and the bank keeps the
        # difference: 8400 B of grids become about a tenth of that.
        blobs, offs = [], []
        for name, grid, _ in tmpls:
            data = "".join(grid).encode("latin1")
            blob = lztmpl.compress(data)
            if lztmpl.expand(blob, len(data)) != data:     # never ship a guess
                raise SystemExit(name + ": LZ round-trip failed")
            offs.append(sum(len(b) for b in blobs))
            blobs.append(blob)

        f.write("/* One LZ stream per template; lz_expand() in leveltmpl.c\n"
                " * unpacks it directly into lvl[][]. */\n")
        f.write("static const uint8_t tmpl_lz[] = {\n")
        for (name, _, _), blob in zip(tmpls, blobs):
            f.write("  /* %s: %d B */\n" % (name, len(blob)))
            for i in range(0, len(blob), 16):
                f.write("  " + ",".join(str(b) for b in blob[i:i + 16]) + ",\n")
        f.write("};\n\n")
        f.write("static const uint16_t tmpl_off[NTMPL] = { %s };\n\n"
                % ", ".join(str(o) for o in offs))

        f.write("static const uint8_t tmpl_nroom[NTMPL] = { %s };\n\n"
                % ", ".join(str(len(r)) for _, _, r in tmpls))

        f.write("static const uint8_t tmpl_room[NTMPL][%d][4] = {\n" % MAXROOM)
        for name, _, rooms in tmpls:
            cells = ["{%d,%d,%d,%d}" % r for r in rooms]
            cells += ["{0,0,0,0}"] * (MAXROOM - len(cells))
            f.write("  { " + ", ".join(cells) + " },\n")
        f.write("};\n")

    packed = sum(len(b) for b in blobs)
    raw = len(tmpls) * MAPW * MAPH
    print("wrote %s  (%d template(s): %s)"
          % (OUT, len(tmpls), ", ".join(n for n, _, _ in tmpls)))
    print("  grids %d B -> %d B packed (%.1f%%), round-trip verified"
          % (raw, packed, 100.0 * packed / raw))


if __name__ == "__main__":
    main()
