#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 Leonardo Roman da Rosa
#
# txt2template.py - pack the hand-drawn special-level maps in
# tools/templates/*.txt into src/leveltmpl_data.h (banked const).
#
#   python tools/txt2template.py
#
# Each .txt is a MAPH x MAPW ASCII map using the normal terrain chars
# ('.' '#' '-' '|' '+' '<' '>' ' '), preceded by metadata comment lines:
#   ;name:  <label>                      (optional, for the C comment)
#   ;rooms: x,y,w,h [x,y,w,h ...]        (1..3 room rects FOV should light)
# Rows shorter than MAPW are padded with rock; missing trailing rows are rock.

from pathlib import Path

HERE = Path(__file__).resolve().parent
TDIR = HERE / "templates"
OUT  = HERE.parent / "src" / "leveltmpl_data.h"
MAPW, MAPH = 80, 21
MAXROOM = 6


def load(path):
    name = path.stem
    rooms, rows = [], []
    for line in path.read_text().splitlines():
        if line.startswith(";rooms:"):
            rooms = [tuple(int(v) for v in tok.split(","))
                     for tok in line[len(";rooms:"):].split()]
        elif line.startswith(";"):
            continue
        else:
            rows.append(line)
    if len(rows) > MAPH:
        raise SystemExit(f"{name}: {len(rows)} map rows > {MAPH}")
    rows += [""] * (MAPH - len(rows))                 # pad trailing rock rows
    grid = []
    for i, r in enumerate(rows):
        if len(r) > MAPW:
            raise SystemExit(f"{name}: row {i} is {len(r)} > {MAPW} cols")
        grid.append(r.ljust(MAPW))
    if not (1 <= len(rooms) <= MAXROOM):
        raise SystemExit(f"{name}: need 1..{MAXROOM} room rects, got {len(rooms)}")
    for (x, y, w, h) in rooms:
        if x + w > MAPW or y + h > MAPH:
            raise SystemExit(f"{name}: room {x},{y},{w},{h} out of bounds")
    return name, grid, rooms


def cstr(s):
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'


def main():
    tmpls = [load(p) for p in sorted(TDIR.glob("*.txt"))]
    if not tmpls:
        raise SystemExit("no templates in " + str(TDIR))
    with OUT.open("w", newline="\n") as f:
        f.write("/* SPDX-License-Identifier: GPL-3.0-or-later\n")
        f.write(" * Copyright (C) 2026 Leonardo Roman da Rosa */\n")
        f.write("/* leveltmpl_data.h - GENERATED by tools/txt2template.py from\n")
        f.write(" * tools/templates/*.txt. Do not edit by hand. Hand-drawn special-\n")
        f.write(" * level maps (MAPH x MAPW) + their room rects, included once into\n")
        f.write(" * the banked leveltmpl.c as PAGE_22 const. */\n\n")
        f.write("#define NTMPL %d\n\n" % len(tmpls))

        f.write("static const char tmpl_map[NTMPL][MAPH][MAPW] = {\n")
        for name, grid, _ in tmpls:
            f.write("  { /* %s */\n" % name)
            for row in grid:
                f.write("    " + cstr(row) + ",\n")
            f.write("  },\n")
        f.write("};\n\n")

        f.write("static const uint8_t tmpl_nroom[NTMPL] = { %s };\n\n"
                % ", ".join(str(len(r)) for _, _, r in tmpls))

        f.write("static const uint8_t tmpl_room[NTMPL][%d][4] = {\n" % MAXROOM)
        for name, _, rooms in tmpls:
            cells = ["{%d,%d,%d,%d}" % r for r in rooms]
            cells += ["{0,0,0,0}"] * (MAXROOM - len(cells))
            f.write("  { " + ", ".join(cells) + " },\n")
        f.write("};\n")

    print("wrote %s  (%d template(s): %s)"
          % (OUT, len(tmpls), ", ".join(n for n, _, _ in tmpls)))


if __name__ == "__main__":
    main()
